# Site settings
author: Felipe Bohórquez
title: RoastedRobots
subtitle: Coding Cheats for Everyone
header-img: img/trex.jpg
email: fbohorqu@hotmail.com
copyright_name: Felipe Bohorquez
description: > # this means to ignore newlines until "baseurl:"
  Brewed by Felipe Bohórquez
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  fbohz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'
    
plugins:
  - jekyll-last-modified-at

gems: [jekyll-paginate, jekyll-feed]
