# Site settings
author: Felipe Bohorquez
title: RoastedRobots
header-img: img/imagecoding.jpg
email: fbohorqu@hotmail.com
copyright_name: Felipe Bohorquez
description: > # this means to ignore newlines until "baseurl:"
  Crafted by Felipe Bohórquez
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  fbohz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
